name: .test-bake

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'releases/v*'
    paths:
      - '.github/workflows/.test-bake.yml'
      - '.github/workflows/bake.yml'
      - '.github/workflows/verify.yml'
      - 'test/**'
  pull_request:
    paths:
      - '.github/workflows/.test-bake.yml'
      - '.github/workflows/bake.yml'
      - '.github/workflows/verify.yml'
      - 'test/**'

jobs:
  bake-dockerhub-single:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      job-name-prefix: bake-dockerhub-single
      cache: true
      cache-scope: bake-dockerhub-single
      context: test
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set: |
        *.args.VERSION={{meta.version}}
      target: hello
      meta-images: |
        docker.io/dockereng/github-builder-test
      meta-tags: |
        type=raw,value=bake-ghbuilder-single-${{ github.run_id }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-dockerhub-single-verify:
    uses: ./.github/workflows/verify.yml
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - bake-dockerhub-single
    with:
      builder-outputs: ${{ toJSON(needs.bake-dockerhub-single.outputs) }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-dockerhub-single-outputs:
    runs-on: ubuntu-24.04
    needs:
      - bake-dockerhub-single
    steps:
      -
        name: Builder outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_BUILDER-OUTPUTS: ${{ toJSON(needs.bake-dockerhub-single.outputs) }}
        with:
          script: |
            const builderOutputs = JSON.parse(core.getInput('builder-outputs'));
            core.info(JSON.stringify(builderOutputs, null, 2));

  bake-dockerhub:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      cache: true
      cache-scope: bake-dockerhub
      context: test
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      runner: |
        default=ubuntu-24.04
        linux/arm=ubuntu-24.04-arm
        linux/arm64=ubuntu-24.04-arm
      sbom: true
      set: |
        *.args.VERSION={{meta.version}}
      target: hello-cross
      meta-images: |
        docker.io/dockereng/github-builder-test
      meta-tags: |
        type=raw,value=bake-ghbuilder-${{ github.run_id }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-dockerhub-verify:
    uses: ./.github/workflows/verify.yml
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - bake-dockerhub
    with:
      builder-outputs: ${{ toJSON(needs.bake-dockerhub.outputs) }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-dockerhub-outputs:
    runs-on: ubuntu-24.04
    needs:
      - bake-dockerhub
    steps:
      -
        name: Builder outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_BUILDER-OUTPUTS: ${{ toJSON(needs.bake-dockerhub.outputs) }}
        with:
          script: |
            const builderOutputs = JSON.parse(core.getInput('builder-outputs'));
            core.info(JSON.stringify(builderOutputs, null, 2));

  bake-dockerhub-scan:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - bake-dockerhub
    steps:
      -
        name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@ffcba8deb5cb3531954cbedbbcd0179d79edf510 # v4.1.0
        with:
          image: docker.io/dockereng/github-builder-test@${{ needs.bake-dockerhub.outputs.digest }}

  bake-dockerhub-nosign:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      cache: true
      cache-scope: bake-dockerhub-nosign
      context: test
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set: |
        *.args.VERSION={{meta.version}}
      sign: false
      target: hello-cross
      meta-images: |
        docker.io/dockereng/github-builder-test
      meta-tags: |
        type=raw,value=bake-ghbuilder-nosign-${{ github.run_id }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-dockerhub-nosign-verify:
    uses: ./.github/workflows/verify.yml
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - bake-dockerhub-nosign
    with:
      builder-outputs: ${{ toJSON(needs.bake-dockerhub-nosign.outputs) }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-dockerhub-nosign-outputs:
    runs-on: ubuntu-24.04
    needs:
      - bake-dockerhub-nosign
    steps:
      -
        name: Builder outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_BUILDER-OUTPUTS: ${{ toJSON(needs.bake-dockerhub-nosign.outputs) }}
        with:
          script: |
            const builderOutputs = JSON.parse(core.getInput('builder-outputs'));
            core.info(JSON.stringify(builderOutputs, null, 2));

  bake-ghcr-and-dockerhub:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      context: test
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set: |
        *.args.VERSION={{meta.version}}
      target: hello-cross
      meta-images: |
        ghcr.io/docker/github-builder-test
        docker.io/dockereng/github-builder-test
      meta-tags: |
        type=raw,value=${{ github.run_id }},prefix=bake-ghcr-and-dockerhub-
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-ghcr-and-dockerhub-verify:
    uses: ./.github/workflows/verify.yml
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - bake-ghcr-and-dockerhub
    with:
      builder-outputs: ${{ toJSON(needs.bake-ghcr-and-dockerhub.outputs) }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-ghcr-and-dockerhub-outputs:
    runs-on: ubuntu-24.04
    needs:
      - bake-ghcr-and-dockerhub
    steps:
      -
        name: Builder outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_BUILDER-OUTPUTS: ${{ toJSON(needs.bake-ghcr-and-dockerhub.outputs) }}
        with:
          script: |
            const builderOutputs = JSON.parse(core.getInput('builder-outputs'));
            core.info(JSON.stringify(builderOutputs, null, 2));

  bake-local:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      artifact-name: bake-output
      artifact-upload: true
      context: test
      output: local
      sbom: true
      sign: ${{ github.event_name != 'pull_request' }}
      target: hello-cross

  bake-local-verify:
    uses: ./.github/workflows/verify.yml
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - bake-local
    with:
      builder-outputs: ${{ toJSON(needs.bake-local.outputs) }}

  bake-local-outputs:
    runs-on: ubuntu-24.04
    needs:
      - bake-local
    steps:
      -
        name: Builder outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_BUILDER-OUTPUTS: ${{ toJSON(needs.bake-local.outputs) }}
        with:
          script: |
            const builderOutputs = JSON.parse(core.getInput('builder-outputs'));
            core.info(JSON.stringify(builderOutputs, null, 2));

  bake-local-single:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      artifact-name: bake-single-output
      artifact-upload: true
      context: test
      output: local
      sbom: true
      sign: ${{ github.event_name != 'pull_request' }}
      target: hello

  bake-local-single-verify:
    uses: ./.github/workflows/verify.yml
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - bake-local-single
    with:
      builder-outputs: ${{ toJSON(needs.bake-local-single.outputs) }}

  bake-local-single-outputs:
    runs-on: ubuntu-24.04
    needs:
      - bake-local-single
    steps:
      -
        name: Builder outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_BUILDER-OUTPUTS: ${{ toJSON(needs.bake-local-single.outputs) }}
        with:
          script: |
            const builderOutputs = JSON.parse(core.getInput('builder-outputs'));
            core.info(JSON.stringify(builderOutputs, null, 2));

  bake-local-noupload:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      artifact-upload: false
      context: test
      output: local
      sbom: true
      target: hello-cross

  bake-local-noupload-verify:
    uses: ./.github/workflows/verify.yml
    needs:
      - bake-local-noupload
    with:
      builder-outputs: ${{ toJSON(needs.bake-local-noupload.outputs) }}

  bake-local-noupload-outputs:
    runs-on: ubuntu-24.04
    needs:
      - bake-local-noupload
    steps:
      -
        name: Builder outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_BUILDER-OUTPUTS: ${{ toJSON(needs.bake-local-noupload.outputs) }}
        with:
          script: |
            const builderOutputs = JSON.parse(core.getInput('builder-outputs'));
            core.info(JSON.stringify(builderOutputs, null, 2));

  bake-local-nosign:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      artifact-name: bake-nosign-output
      artifact-upload: true
      context: test
      output: local
      sbom: true
      sign: false
      target: hello-cross

  bake-local-nosign-verify:
    uses: ./.github/workflows/verify.yml
    needs:
      - bake-local-nosign
    with:
      builder-outputs: ${{ toJSON(needs.bake-local-nosign.outputs) }}

  bake-local-nosign-outputs:
    runs-on: ubuntu-24.04
    needs:
      - bake-local-nosign
    steps:
      -
        name: Builder outputs
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_BUILDER-OUTPUTS: ${{ toJSON(needs.bake-local-nosign.outputs) }}
        with:
          script: |
            const builderOutputs = JSON.parse(core.getInput('builder-outputs'));
            core.info(JSON.stringify(builderOutputs, null, 2));

  bake-set-runner:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      runner: ubuntu-24.04
      context: test
      output: image
      push: false
      set: |
        *.args.VERSION={{meta.version}}
      target: hello-cross
      meta-images: |
        docker.io/dockereng/github-builder-test
      meta-tags: |
        type=raw,value=bake-ghbuilder-${{ github.run_id }}

  bake-set-runner-deprecated:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      runner: amd64
      context: test
      output: image
      push: false
      set: |
        *.args.VERSION={{meta.version}}
      target: hello-cross
      meta-images: |
        docker.io/dockereng/github-builder-test
      meta-tags: |
        type=raw,value=bake-ghbuilder-${{ github.run_id }}

  bake-qemu:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      setup-qemu: true
      artifact-upload: false
      context: test
      output: local
      sbom: true
      target: hello-cross

  bake-dockerhub-nodistrib:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      distribute: false
      cache: true
      cache-scope: bake-dockerhub-nodistrib
      context: test
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set: |
        *.args.VERSION={{meta.version}}
      target: hello-cross
      meta-images: |
        docker.io/dockereng/github-builder-test
      meta-tags: |
        type=raw,value=bake-ghbuilder-nodistrib-${{ github.run_id }}
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKERPUBLICBOT_USERNAME }}
          password: ${{ secrets.DOCKERPUBLICBOT_WRITE_PAT }}

  bake-local-nodistrib:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      distribute: false
      artifact-name: bake-nodistrib-output
      artifact-upload: true
      context: test
      output: local
      sbom: true
      sign: ${{ github.event_name != 'pull_request' }}
      target: hello-cross

  bake-vars:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      setup-qemu: true
      artifact-upload: false
      context: test
      output: local
      target: go
      vars: |
        XX_VERSION=1.9.0

  bake-auth-scope:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      context: test
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set: |
        *.args.VERSION={{meta.version}}
      target: hello-cross
      meta-images: |
        ghcr.io/docker/github-builder-test
      meta-tags: |
        type=raw,value=bake-ghbuilder-scope-${{ github.run_id }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          scope: '@push'

  bake-auth-scope-verify:
    uses: ./.github/workflows/verify.yml
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - bake-auth-scope
    with:
      builder-outputs: ${{ toJSON(needs.bake-auth-scope.outputs) }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  bake-namedcontexts:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
    with:
      artifact-name: bake-namedcontexts-output
      artifact-upload: true
      context: test
      output: local
      sbom: true
      sign: ${{ github.event_name != 'pull_request' }}
      target: go-cross-with-contexts

  bake-ghcr-index-annotations:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      context: test
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set: |
        *.args.VERSION={{meta.version}}
      target: hello-cross
      set-meta-annotations: true
      meta-images: ghcr.io/docker/github-builder-test
      meta-tags: |
        type=raw,value=bake-index-annotations-${{ github.run_id }}
      meta-annotations: |
        io.github.docker.github-builder.test-index-annotation=bake-${{ github.run_id }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  bake-ghcr-image-casing:
    uses: ./.github/workflows/bake.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      context: test
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      sbom: true
      set: |
        *.args.VERSION={{meta.version}}
      target: hello-cross
      set-meta-annotations: true
      meta-images: ghcr.io/docker/GitHub-Builder-Test
      meta-tags: |
        type=raw,value=bake-image-casing-${{ github.run_id }}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
